return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "delve",
      "eslint-lsp",
      "go-debug-adapter",
      "gofumpt",
      "goimports",
      "gomodifytags",
      "gopls",
      "gotests",
      "impl",
      "jq",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "mypy",
      "prettier",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "stylua",
      "terraform-ls",
      -- "typescript-language-server",
      "yaml-language-server",
    },
  },
}
